### ISSUE TITLE
Add a (social) interaction

### ISSUE THREAD

**Issue by josch87** [josch87/Gunther#15]
## Value proposition

As a user
I want to add a social interaction
So that I can preserve important interaction details with contacts for the future

## Description

![Image](https://github.com/josch87/Gunther/assets/33511915/0f4d601d-c4c1-496b-b9fe-947d5afbaa8c)

## Acceptance criteria

- [ ] When clicking the plus icon in the header instead of leading to the "Add new contact" page it opens a dropdown menu.
- [ ] The dropdown menu has two first-level-items saying "New contact" and "New interaction"
- [ ] "New contact" leads to the "Add new contact" page. "New interaction" leads to the "Add new interaction" page.
- [x]  "Add new interaction" page displays a form where I can enter the following information:
  - [x] Interaction (Dropdown; possible values: "Phone call", "Party" ... (baseData)
  - [x] For interactions you can also insert a custom value
  - [x] Date the interaction took place
  - [x] Participants (Dropdown where you can select one or multiple excisting contacts)
  - [x] Notes (Textarea, up to 600 characters, line break possible)
- [x] A Save and Cancel button are visible below the form
- [x] Clicking on the save button saves the entered form data and leads you to the detail page of the newly created interaction
- [x] Clicking on the cancel button leads you back to the previous page you have been to.

**Comment by NilsOt1** [comment]
Nice feature!
One little issue. On the description wireframe there is an additional "who called" but I can't find it in the acceptance criteria

**Comment by josch87** [comment]
Yes, I simplified the US a bit for the MVP 'coz this is an advanced feature but was to lazy to delete it from the wireframe as well (maybe I have the time/ideas to implement it right with it...). I modified the wireframe now in order not to confuse the developers.
