### ISSUE TITLE
Show contact details

### ISSUE THREAD

**Issue by josch87** [josch87/Gunther#2]
## Value proposition

As a user
I want to see details for each contact
So that I can see contact information and my notes about that contact

## Description

![Image](https://user-images.githubusercontent.com/33511915/250945563-d82b8765-8c04-45d1-98ed-b03c9d0d0f3d.png)

## Acceptance criteria

- [x] A single contact list item links to a new page showing contact details for the clicked contact
- [x] The contact details page displays a back button which leads back to the list of all contacts
- [x] The contact details page displays a scopebox with all contact details
- [x] The scopebox has a heading section displaying the following data:
  - Profile Picture/Placeholder
  - First name (NOT NULLABLE), middle name, last name (no unnecessary spaces please)
  - Birthday
- [x] The scopebox has a section labeled "Contact Details" showing the following fields:
  - Email / Type (types can have values like "Home", "Work" or "Other")
  - Phone / Type
  - Address / Type
  - Nickname
  - Instagram username
  - Twitter username
  - Notes (textarea with up to 500 characters)
- [x] Clicking on a contact details field value performs an action
  - email: Opening a new email in the default client with address prefilled
  - phone: Starting a call with the default client
  - Instagram: Open instagram profile in new tab
  - address: open location in Google Maps
- [x] All contact detail fields are NULLABLE
- [x] If a field is NULL, it won't be displayed

**Comment by VolkerJacobsen** [comment]
Looks good to me but the userstory is quite detailed. Would it maybe make sense to write an additional userstory for "Clicking on contact" part?

**Comment by josch87** [comment]
I personally think clicking on a field is not very complex. It is just an anchor-element that leads to a target. 

Instead of writing
`Instagram: aljoschazoeller`
you are writing
`Instagram: <a href="https://www.instagram.com/aljoschazoeller/" target="_blank">aljoschazoeller</a>`

Therefor I would like to keep it in this user story. 

Thanks for the thought, though!
