### ISSUE TITLE
Edit a (social) interaction

### ISSUE THREAD

**Issue by josch87** [josch87/Gunther#22]
## Value proposition

As a user
I want to edit a (social) interaction
So that I can add or modify interaction details that I had with contacts

## Description

![Image](https://user-images.githubusercontent.com/33511915/254503886-be78a6c3-c513-4c84-81a1-a4676529155f.png) ![Image](https://user-images.githubusercontent.com/33511915/254503747-d2a3ea7e-aa84-4577-aaf2-69d26ca5ebee.png)

## Acceptance criteria

- [x] Social Interaction Details page is displaying an edit button that leads to the edit page
- [x] The edit page displays all form inputs and Cancel + Save Button as in [#15](https://github.com/josch87/Gunther/issues/15)
- [x] All fields are filled out with the existing data for the selected interaction on page load
- [x] A Save and Cancel button are visible below the form
- [x] Clicking the save button persists the changes and leads back to the interaction detail page of the interaction
- [x] Clicking the cancel button does not persist any changes and leads back to interaction detail page of the interaction

**Comment by NilsOt1** [comment]
LGTM 🤝
