### ISSUE TITLE
Delete a (social) interaction

### ISSUE THREAD

**Issue by josch87** [josch87/Gunther#24]
## Value proposition

As a user
I want to delete a (social) interaction
So that I can get rid of duplicates

## Description

![Image](https://user-images.githubusercontent.com/33511915/254602907-3f47bd2b-2eef-4ba8-b5a0-15822ca58721.png) ![Image](https://user-images.githubusercontent.com/33511915/254602708-5817454b-1a9c-4730-a0db-e81fd21a0ce8.png)

## Acceptance criteria

- [x] Interaction Details Page is displaying a delete button that opens a delete modal
- [x] The delete modal is showing a checkbox where the user needs to confirm that he/she understands the action and its impact
- [x] A "Delete interaction" and "Cancel" button are visible below the checkbox
- [x] As long as the checkbox is not checked the "Delete interaction" button is inactive
- [x] Clicking the "Delete interaction" button flags the interaction as deleted in the data, saves the timestamp of the deletion, closes the modal and leads back to "All interactions" page. It does not delete the object
- [x] Clicking the "Cancel" button does not perform any action to the data and closes the modal

**Comment by ekat-br** [comment]
Hi Aljoscha! I'm missing the tasks of the user story. Is there a reason for that?

**Comment by josch87** [comment]
Hi @ekat-br! Thanks for your watchful eye! I don't write tasks on purpose at this stage. Tasks are not part of the original user story and product owners should not dictate the scrum developers **how** the requirements are going to be implemented. 

During the [Sprint Planning](https://scrumguides.org/scrum-guide.html#sprint-planning), the Scrum Team (Developers, Product Owner, Scrum Master) addresses the following topics:
1. **Why** is this Sprint valuable?
The PO proposes how the team can increase the value of the product during the sprint. The whole team works together to define a Sprint Goal (the Sprint Backlog Artifact) on which the team then has to commit. 
2. **What** can be Done this Sprint?
The team discusses with the PO which Product Backlog Items (PBIs) - these can be in the form of User Stories - to select in order to work towards the Sprint Goal. In order to know how many PBIs can be done this sprint they can relatively estimate the costs of each PBI. They can do this using Story Points and use T-shirt sizes or - most of the time - the (modified) Fibonacci sequence as a unit. Instead of Story Points they can work with [Function Points](https://en.wikipedia.org/wiki/Function_point) if an ISO Standard is needed or [Use Case Points](https://en.wikipedia.org/wiki/Use_case_points) if they work with Use Cases before breaking down to User Stories. In order to agree on the costs (everyone has a different knowledge about the project/code/technology/feature and a different look at the subject) and discuss the size, they can play Scrum Poker (also called Planning Poker). The product owner answers questions which might arise, for example regarding the acceptance criteria. In exchange with the PO, the entire team gets a better understanding of the user story and they refine it (what they hopefully also did regularly before in the product backlog).
3. **How** will the chosen work get done?
All wh-questions are influenced or even predetermined by product owners and other factors that the team might have no influence on (project managers, CEOs, clients, the market, ---> Stakeholders), except one: The **how** belongs to the developers. All developers (if we talk about software they can consist of disciplines like frontend engineers, backend engineers, database engineers, UI/UX designer, software/solution architect etc.) discuss what needs to happen in order to get the user stories done. It is not predetermined by the Scrum Guide how this has to be organized. 
A lot of teams write a seperate ticket for each task and put them into the Sprint Backlog. This way they can split the work that needs to be done for each user story into the disciplines which are represented in the team. 

As you have currently (at least) two roles in this bootcamp (PO and DEV) and you are the only developer in your scrum team, it might help you in the beginning to write your tasks below the user story right away. However, this is not taken over by the PO and the organization of the tasks depends on the agreements in the team.

**Comment by ekat-br** [comment]
Thank you very much for your very detailed answer @josch87 , which I would like to respond to in equal detail. 

I have already had the opportunity to work in a Scrum team, so I have a good general understanding of the Scrum process and I am also curious to learn new things about it. 

I agree with you that the "how" is not given in the Scrum Guide. And I understand that you want to stick to the generally recommended Scrum process. 

I just started with the first user stories today and I was told by two coaches how the Scrum process works at neuefische and it was recommended to stick to the process. From my point of view, the tasks contained in the user story are very useful because you can roughly structure your approach and get direct feedback. 


Since I will stick to neuefische's procedure and think it makes sense to have a uniform process, I cannot approve your story. I would like to hear from a coach that it is possible to drop tasks in the user story. Maybe I will reconsider my opinion.

I hope my point of view is understandable.

**Comment by ekat-br** [comment]
Hi @josch87, 

today I was able to talk to my coach and find out that your course received different information regarding the user stories than ours. Therefore, I would like to overlook the fact that you do not use tasks and still give you feedback.

Your user story is very well described. It is understandable and there is nothing I can add. Keep up the good work 🚀
