### ISSUE TITLE
Upload profile picture for each contact

### ISSUE THREAD

**Issue by josch87** [josch87/Gunther#28]
## Value proposition

As a user
I want to upload pictures to my contacts
So that I can see on first sight who they are

## Description

![Image](https://user-images.githubusercontent.com/33511915/255553331-4268ab38-c982-4bb4-bad6-576cc6bfcb8b.png)

## Acceptance criteria

- [x] "Contact Add Page" & "Contact Edit Page" are displaying an upload element
- [x] Clicking the upload element opens a modal where I can select a file from my disk space
- [x] allowed file endings are JPG, JPEG, PNG, WEBP
- [x] After uploading, the file is cropped to a rectangle and displayed in the ContactDetailsHeader
- [x] The file is stored permanently and will be displayed every time the contact list page, contact details page or contact edit page are loaded
- [x] Uploading another file overwrites the currently stored image

**Comment by mrrubinello** [comment]
ok
