### ISSUE TITLE
Add an app header

### ISSUE THREAD

**Issue by josch87** [josch87/Gunther#3]
## Value proposition

As a user
I want to see an app header
So that I can see in which app I currently am

## Description

![Image](https://user-images.githubusercontent.com/33511915/251104893-3f81e44e-6bc2-4e6f-b809-397f00a8d79f.png)

## Acceptance criteria

- [ ] App header is being displayed fixed on top of the viewport
- [ ] The app logo is displayed centered inside the app header
- [ ] The header is part of the default layout and is displayed on all (future) pages

**Comment by vaupunkt** [comment]
lgtm :) 
I think you could be more detailed on where your default layout is located or how you are going to code it, but I think it doesn't matter at this point :)

**Comment by josch87** [comment]
As a product owner I do not want to tell the developers HOW to implement the features. In a user story I only deliver the requirements to them (in user perspective) and they need to discuss on HOW to implement the features to satisfy the requirements. 

As a developer I can write new tasks when I work on the US and relate them to the original user story (as sub tasks).
