### ISSUE TITLE
"Upcoming events" Dashboard Widget

### ISSUE THREAD

**Issue by josch87** [josch87/Gunther#32]
## Value proposition

As a user
I want to see upcoming events on the homepage
So that I don't miss out on a party already added as future interaction

## Description

![Image](https://github.com/josch87/Gunther/assets/33511915/023d7650-031b-4690-a0f9-f0eda4dc5479)

## Acceptance criteria

- [x] A new Homepage is displaying a dashboard
- [x] The navigation menu is displaying an item to navigate to the dashboard
- [x] The dashboard is displaying a section "Upcoming"
- [x] In the "Upcoming" section up to three interactions are displayed that are about to happen in the future
- [x] The interactions are sorted by dateOfInteraction with the closest date on top

**Comment by josch87** [comment]
The user story does not say what to do when there are no interactions in the future that can be displayed. Should the widget say so or should the whole widget not render?

**Comment by josch87** [comment]
- Telling the user that there are no upcoming events: https://gunther-qp6lgo528-josch87.vercel.app/
- Don't show widget at all when there are no upcoming events: https://gunther-8s01bxcyo-josch87.vercel.app/

**Comment by josch87** [comment]
Decided to not show the widget at all when there are no upcoming events. 
Dashboard might be empty for now but there are gonna be some dashboard widgets to come soon. Thinking about adding a paragraph as welcome note as well as when there are no upcoming interactions for now.

**Comment by josch87** [comment]
Added a welcome message thats showing unconditionally. Could implement function later on to make the user hide it.

**Comment by BirkBee** [comment]
Hey Josch, very nice app so far! 🙌  I really like how complex your forms are and that you have multiple helpful pop ups after submitting. 
You change quite a few things in your code, but it looks good to me. Your Website seems to work with the implementations you wanted to add with this US. Your wireframe looks a little bit different from what your app looks now, but I'm sure you are aware of this. LGTM 🚀 🙌
