### ISSUE TITLE
Add notifications for user actions

### ISSUE THREAD

**Issue by josch87** [josch87/Gunther#34]
## Value proposition

As a user
I want to see a notification after a create/write/delete operation
So that I can make sure that the data got modified

## Description

![Image](https://user-images.githubusercontent.com/33511915/256287170-74095d16-9823-4b9f-a799-04ffc86d6e01.png)

## Acceptance criteria

- [ ] After successfully creating, updating or deleting an entity (contact, interaction, file upload), the user gets notified that the change happened
- [ ] When an error occurred during the creation/update/deletion of an entity, the user gets notified with an error message

**Comment by FlorianNova** [comment]
lgtm
