### ISSUE TITLE
Styling / Refactoring / Readme

### ISSUE THREAD

**Issue by josch87** [josch87/Gunther#38]
## Value proposition

As a user
I want to have a contemporary-designed user interface with intuitive functions
So that I can enjoy using all its features without any confusion

## Acceptance criteria

- [ ] The app's user interface has a contemporary design that the user enjoys using.
- [ ] Functions are easy to recognize, so users can anticipate behavior when an element is clicked.
- [ ] The `Readme.md` contains meaningful information for end-users as well as instructions for developers to run the app locally.
- [ ] The code is refactored so that it can be read and understood easily.

**Comment by AliaksandraNovikava** [comment]
LGTM👍
