### ISSUE TITLE
"Activity" Dashboard Widget

### ISSUE THREAD

**Issue by josch87** [josch87/Gunther#46]
## Value proposition

As a user,
I want a dashboard widget labeled "Activities"
So that I can quickly view my latest interactions with the app.

## Description

![Image](https://github.com/josch87/Gunther/assets/33511915/ace99f69-0ee4-4fbd-a947-52007b60ac68)

## Acceptance criteria

**1. Create, Update, and Delete Logging:**
  - [x] Activities should be logged for all existing entities, specifically contacts and interactions.
  - [x] Logging should capture Create, Update, and Delete operations.

**2. Dashboard "Activities" Section:**
  - [x] The dashboard should have a dedicated section labeled "Activities."

**3. Display Latest Activities:**
  - [x] The "Activities" section should display up to the last five activities.
  - [x] The displayed activities should show which object (entity) was modified.
  - [x] Each displayed activity should include an icon representing the operation used (Create, Update, Delete).

**4. Information Display:**
  - [x] The day of when the activity occurred should be displayed for each entry.
  - [x] When the activity occurred today, display the minutes or hours that have passed since the action.
  - [x] For activities within the last 7 days, display "yesterday" or "X days ago."
  - [x] Implement hover functionality to show the complete timestamp with day and time.

**5. Sorting:**
  - [x] Activities should be sorted by the date of activity, with the most recent activity displayed at the top.

**Comment by Roland-Hufnagel** [comment]
Very detailed and complex userstory. Great! 💪 Have fun working on it. 👍
