### ISSUE TITLE
Show a list of all (social) interactions

### ISSUE THREAD

**Issue by josch87** [josch87/Gunther#6]
## Value proposition

As a user
I want to see a list of all (social) interactions
So that I know which interactions I had in the past with friends and family

## Description

![Image](https://user-images.githubusercontent.com/33511915/251213686-9f8bbb4f-5fc2-40e1-8221-955a473f1293.png)

## Acceptance criteria
- [x] Every (social) interaction is in a list item below each other
- [x] The list has a heading that says "Interactions"
- Each list item displays the following information:
  - [x] Icon that shows the type of the interaction. Types can be:
    - call
    - incoming-call
    - outgoing-call
    - video-conference
    - party
    - other
  - [x] Contacts, that are referenced as participants of the interaction (alphabetically by first name)
    - [x] Participants last names are shortened (no unnecessary spaces) in order to have room for multiple contacts
  - [x] Date, the interaction took place
- [x] Items are sorted by interactionDate on default, latest on top

**Comment by DErdmann1** [comment]
lgtm :) It's so detailed! 
I'm very excited about your project.
