### ISSUE TITLE
Add mobile navigation

### ISSUE THREAD

**Issue by josch87** [josch87/Gunther#7]
## Value proposition

As a user
I want to navigate between pages
So that I can switch between contact & interactions list

## Description

![Image](https://user-images.githubusercontent.com/33511915/251214187-49325cfe-d447-4866-9a57-c1419b4c67b7.png)

## Acceptance criteria

- [x] A navigation bar is displayed fixed at the bottom of each page as part of the default layout
- [x] There are two navigation items that represent the pages "Contacts" and "Interactions"
- [x] Every nav item shows an icon that is related to the page it is representing
- [x] Clicking on a nav item leads to the represented page
- [x] Hovering over the nav item (or touching and holding the nav bar item with the finger) displays a tooltip explaining the context: "Contacts", "Interactions"
- [x] The navigation is accessible
- [x] A background color on the nav item indicated which page you are currently visiting

**Comment by JessicaLoers** [comment]
Well done, @josch87   👍
